version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-sid

    working_directory: ~/repo
    
    steps:
      - checkout

      - run:
          command: |
            cd noconstructors && mvn install --batch-mode --errors && cd ..
            cd noconstructors-bytebuddy && mvn install --batch-mode --errors && cd ..
            cd noconstructors-javac && mvn install --batch-mode --errors && cd ..
            cd noconstructors-bytebuddy-maven-example && mvn install --batch-mode --errors && cd ..
            cd noconstructors-javac-maven-example && mvn install --batch-mode --errors && cd ..